[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## 有疑问或者其他的设计

### 编译问题

## 必须要掌握的知识

### 网络流程

#### 通信架构流程

#### 协议生成流程

### 关键概念

#### Fiber

##### 类似Erlang的进程

##### 线程调度

###### 3种调度方式

##### Fiber间通信的Actor消息机制

#### Scene

### 打包和部署

#### 只当客户端的方式

#### 当双端的方式

### 数据库的操作

### ECS 设计概念和代码规范
