[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## 客户端连接服务端的配置

### ConstValue\.cs

## 服务器的起服配置
> leftSide=`true`


### StartMachineConfig

## 自己本地局域网测试
> leftSide=`true`


### 跟服务器不在一个服务器的设备连接不上的问题

#### 简单的关闭防火墙验证一下是不是防火墙拦住了<br/>这里就验证过是会的

### 只是在初次启动的时候允许连接好像还是不行

### 创建入站规则

#### 高级安全 Windows Defender防火墙

#### 类型选 "程序"
> leftSide=`true`


#### 下一步选择规则应用于特性程序，路径选择到Bin/app\.exe
> leftSide=`true`


#### 如果只是选择特性程序还是不行的话，要新建入站规则，<br/>选择端口类型，并且设置ConstValue里面的端口可以连接

## 服务器App的生成路径

### 仓库目录 bin\\app\.exe
