[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## 调用接口 TransferHelper\.Transfer

### 发送M2M\_UnitTransferRequest

### M2M\_UnitTransferRequestHandler

#### 反序列化Unit，并且添加到UnityComponent

#### 反序列化请求的Entity数据

#### 给Unity添加移动和寻路组件

#### 通知客户端开始切场景

##### M2C\_StartSceneChange

###### 这里如果Unity的InstanceId找不到MailBox的话，只会输出警告<br/>然后什么反应都没有

#### 通知客户端创建MyUnit

#### 加入AOI
