[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Root topic

## 起服配置

### StartSceneConfig\.xlsx

#### StarttSceneConfig页签配的的都是zone（区）为1的服

#### Router页签都是区服为三的

#### 公共服 配Realm为登录服为 zone为10000

### StartZoneConfig\.xlsx

#### StartSceneConfig配的Zone作为key查询这个表

#### 配置数据库地址，数据库名
